Bump ahooks from 3.8.0 to 3.8.1 (#146)
Bumps [ahooks](https://github.com/alibaba/hooks) from 3.8.0 to 3.8.1.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/alibaba/hooks/releases">ahooks's
releases</a>.</em></p>
<blockquote>
<h2>v3.8.1</h2>
<h2>What's Changed</h2>
<ul>
<li>🐛 fix(useResponse): adds default export by <a
href="https://github.com/CJY0208"><code>@​CJY0208</code></a> in <a
href="https://redirect.github.com/alibaba/hooks/pull/2555">alibaba/hooks#2555</a></li>
<li>🐛 fix(useSelections): <code>setSelected</code> should support
non-array value by <a
href="https://github.com/liuyib"><code>@​liuyib</code></a> in <a
href="https://redirect.github.com/alibaba/hooks/pull/2559">alibaba/hooks#2559</a></li>
<li>🐛 fix(useResetState): reset random initial value incorrectly by <a
href="https://github.com/hemengke1997"><code>@​hemengke1997</code></a>
in <a
href="https://redirect.github.com/alibaba/hooks/pull/2562">alibaba/hooks#2562</a></li>
<li>🐛 fix: resolves depsEqual performance issues by <a
href="https://github.com/caorushizi"><code>@​caorushizi</code></a> in <a
href="https://redirect.github.com/alibaba/hooks/pull/2578">alibaba/hooks#2578</a></li>
<li>🐛 fix: <code>TypeError: props.hasOwnProperty is not a
function</code> by <a
href="https://github.com/ShaofeiZi"><code>@​ShaofeiZi</code></a> in <a
href="https://redirect.github.com/alibaba/hooks/pull/2596">alibaba/hooks#2596</a></li>
<li>🐛 fix: resolves useRquest debounce issue by <a
href="https://github.com/ruixingshi"><code>@​ruixingshi</code></a> in <a
href="https://redirect.github.com/alibaba/hooks/pull/2606">alibaba/hooks#2606</a></li>
<li>🐛 fix: solve the compatibility issue of useLongPress on desktop
Safari by <a
href="https://github.com/mscststs"><code>@​mscststs</code></a> in <a
href="https://redirect.github.com/alibaba/hooks/pull/2602">alibaba/hooks#2602</a></li>
<li>🛠 chore(useRequest): the official useRequest hooks documentation has
an error. In version 2, the option parameter should be throwOnError by
<a href="https://github.com/chovrio"><code>@​chovrio</code></a> in <a
href="https://redirect.github.com/alibaba/hooks/pull/2563">alibaba/hooks#2563</a></li>
<li>🛠 chore: bump js-cookie to ^3.0.5 by <a
href="https://github.com/fisherspy"><code>@​fisherspy</code></a> in <a
href="https://redirect.github.com/alibaba/hooks/pull/2600">alibaba/hooks#2600</a></li>
<li>🤖 ci: &quot;intall&quot; word error, should be &quot;install&quot;
by <a href="https://github.com/long36708"><code>@​long36708</code></a>
in <a
href="https://redirect.github.com/alibaba/hooks/pull/2587">alibaba/hooks#2587</a></li>
<li>🤖 ci: change node.js version to 18, 20 and update actions version by
<a href="https://github.com/liuyib"><code>@​liuyib</code></a> in <a
href="https://redirect.github.com/alibaba/hooks/pull/2604">alibaba/hooks#2604</a></li>
<li>⚡ test: update useLatest test case by <a
href="https://github.com/FEliuyg"><code>@​FEliuyg</code></a> in <a
href="https://redirect.github.com/alibaba/hooks/pull/2586">alibaba/hooks#2586</a></li>
<li>📚 docs: fix the Chinese mirror by <a
href="https://github.com/zhangmo8"><code>@​zhangmo8</code></a> in <a
href="https://redirect.github.com/alibaba/hooks/pull/2608">alibaba/hooks#2608</a></li>
</ul>
<hr />
<ul>
<li>🐛 fix(useResponse): 添加默认导出，由 <a
href="https://github.com/CJY0208"><code>@​CJY0208</code></a> 提交于 <a
href="https://redirect.github.com/alibaba/hooks/pull/2555">alibaba/hooks#2555</a></li>
<li>🐛 fix(useSelections): <code>setSelected</code> 应该支持非数组值，由 <a
href="https://github.com/liuyib"><code>@​liuyib</code></a> 提交于 <a
href="https://redirect.github.com/alibaba/hooks/pull/2559">alibaba/hooks#2559</a></li>
<li>🐛 fix(useResetState): 重置随机初始值错误，由 <a
href="https://github.com/hemengke1997"><code>@​hemengke1997</code></a>
提交于 <a
href="https://redirect.github.com/alibaba/hooks/pull/2562">alibaba/hooks#2562</a></li>
<li>🐛 fix: 解决 depsEqual 性能问题，由 <a
href="https://github.com/caorushizi"><code>@​caorushizi</code></a> 提交于
<a
href="https://redirect.github.com/alibaba/hooks/pull/2578">alibaba/hooks#2578</a></li>
<li>🐛 fix: 修复 <code>TypeError: props.hasOwnProperty is not a
function</code> 由 <a
href="https://github.com/ShaofeiZi"><code>@​ShaofeiZi</code></a> 提交于 <a
href="https://redirect.github.com/alibaba/hooks/pull/2596">alibaba/hooks#2596</a></li>
<li>🐛 fix: 解决 useRquest 防抖问题，由 <a
href="https://github.com/ruixingshi"><code>@​ruixingshi</code></a> 提交于
<a
href="https://redirect.github.com/alibaba/hooks/pull/2606">alibaba/hooks#2606</a></li>
<li>🐛 fix: 解决 useLongPress 在桌面端 Safari 不兼容的问题，由 <a
href="https://github.com/mscststs"><code>@​mscststs</code></a> 提交于 <a
href="https://redirect.github.com/alibaba/hooks/pull/2602">alibaba/hooks#2602</a></li>
<li>🛠 chore(useRequest): 官方文档 useRequest hooks 文案错误，v2 中的 option 参数应该是
throwOnError，由 <a
href="https://github.com/chovrio"><code>@​chovrio</code></a> 提交于 <a
href="https://redirect.github.com/alibaba/hooks/pull/2563">alibaba/hooks#2563</a></li>
<li>🛠 chore: 将 js-cookie 升级到 ^3.0.5，由 <a
href="https://github.com/fisherspy"><code>@​fisherspy</code></a> 提交于 <a
href="https://redirect.github.com/alibaba/hooks/pull/2600">alibaba/hooks#2600</a></li>
<li>🤖 ci: &quot;intall&quot; 单词错误，应为 &quot;install&quot;，由 <a
href="https://github.com/long36708"><code>@​long36708</code></a> 提交于 <a
href="https://redirect.github.com/alibaba/hooks/pull/2587">alibaba/hooks#2587</a></li>
<li>🤖 ci: 将 node.js 版本更改为 18、20 并更新 actions 版本，由 <a
href="https://github.com/liuyib"><code>@​liuyib</code></a> 提交于 <a
href="https://redirect.github.com/alibaba/hooks/pull/2604">alibaba/hooks#2604</a></li>
<li>⚡ test: 更新 useLatest 测试用例，由 <a
href="https://github.com/FEliuyg"><code>@​FEliuyg</code></a> 提交于 <a
href="https://redirect.github.com/alibaba/hooks/pull/2586">alibaba/hooks#2586</a></li>
<li>📚 docs: 修复中文镜像，由 <a
href="https://github.com/zhangmo8"><code>@​zhangmo8</code></a> 提交于 <a
href="https://redirect.github.com/alibaba/hooks/pull/2608">alibaba/hooks#2608</a></li>
</ul>
<h2>New Contributors</h2>
<ul>
<li><a href="https://github.com/chovrio"><code>@​chovrio</code></a> made
their first contribution in <a
href="https://redirect.github.com/alibaba/hooks/pull/2563">alibaba/hooks#2563</a></li>
<li><a
href="https://github.com/caorushizi"><code>@​caorushizi</code></a> made
their first contribution in <a
href="https://redirect.github.com/alibaba/hooks/pull/2578">alibaba/hooks#2578</a></li>
<li><a href="https://github.com/long36708"><code>@​long36708</code></a>
made their first contribution in <a
href="https://redirect.github.com/alibaba/hooks/pull/2587">alibaba/hooks#2587</a></li>
<li><a href="https://github.com/FEliuyg"><code>@​FEliuyg</code></a> made
their first contribution in <a
href="https://redirect.github.com/alibaba/hooks/pull/2586">alibaba/hooks#2586</a></li>
<li><a href="https://github.com/ShaofeiZi"><code>@​ShaofeiZi</code></a>
made their first contribution in <a
href="https://redirect.github.com/alibaba/hooks/pull/2596">alibaba/hooks#2596</a></li>
<li><a href="https://github.com/mscststs"><code>@​mscststs</code></a>
made their first contribution in <a
href="https://redirect.github.com/alibaba/hooks/pull/2602">alibaba/hooks#2602</a></li>
<li><a href="https://github.com/zhangmo8"><code>@​zhangmo8</code></a>
made their first contribution in <a
href="https://redirect.github.com/alibaba/hooks/pull/2608">alibaba/hooks#2608</a></li>
<li><a
href="https://github.com/ruixingshi"><code>@​ruixingshi</code></a> made
their first contribution in <a
href="https://redirect.github.com/alibaba/hooks/pull/2606">alibaba/hooks#2606</a></li>
<li><a href="https://github.com/fisherspy"><code>@​fisherspy</code></a>
made their first contribution in <a
href="https://redirect.github.com/alibaba/hooks/pull/2600">alibaba/hooks#2600</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/alibaba/hooks/compare/v3.8.0...v3.8.1">https://github.com/alibaba/hooks/compare/v3.8.0...v3.8.1</a></p>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/alibaba/hooks/commit/f46d77aeeee0ae79b922e8a19a96cf82a0ef0f21"><code>f46d77a</code></a>
chore: update version</li>
<li><a
href="https://github.com/alibaba/hooks/commit/3905729c66e902b1c25c15476db3832823210dd3"><code>3905729</code></a>
chore: bump js-cookie to ^3.0.5 (<a
href="https://redirect.github.com/alibaba/hooks/issues/2600">#2600</a>)</li>
<li><a
href="https://github.com/alibaba/hooks/commit/ac46912d00832bb2f6f3bbdcff9ebe4a2e970ee3"><code>ac46912</code></a>
fix: resolves useRquest debounce issue (<a
href="https://redirect.github.com/alibaba/hooks/issues/2606">#2606</a>)</li>
<li><a
href="https://github.com/alibaba/hooks/commit/7fad40bae29e52aec61a1fbdcbe13d67f1ad400f"><code>7fad40b</code></a>
docs: fix the Chinese mirror (<a
href="https://redirect.github.com/alibaba/hooks/issues/2608">#2608</a>)</li>
<li><a
href="https://github.com/alibaba/hooks/commit/3bd192572fc65c98eb5701453e5ea09644b669f1"><code>3bd1925</code></a>
fix: 解决桌面端 Safari 不兼容 TouchEvent 的问题 (<a
href="https://redirect.github.com/alibaba/hooks/issues/2602">#2602</a>)</li>
<li><a
href="https://github.com/alibaba/hooks/commit/2bc738f72f6487fea208a2c4a3992e3748613dff"><code>2bc738f</code></a>
ci: change node.js version to 18,20 and update actions version (<a
href="https://redirect.github.com/alibaba/hooks/issues/2604">#2604</a>)</li>
<li><a
href="https://github.com/alibaba/hooks/commit/d4afca3747e7aab4bdf7cb9fe8d7e7f891d6a762"><code>d4afca3</code></a>
fix: TypeError: props.hasOwnProperty is not a function (<a
href="https://redirect.github.com/alibaba/hooks/issues/2596">#2596</a>)</li>
<li><a
href="https://github.com/alibaba/hooks/commit/b2f12185963b7efe46ec70c97f661849f89892b5"><code>b2f1218</code></a>
test: update useLatest test case (<a
href="https://redirect.github.com/alibaba/hooks/issues/2586">#2586</a>)</li>
<li><a
href="https://github.com/alibaba/hooks/commit/47403c16a03a5673191182f844b627769be1e3e6"><code>47403c1</code></a>
ci: &quot;intall&quot; word error,should &quot;install&quot; (<a
href="https://redirect.github.com/alibaba/hooks/issues/2587">#2587</a>)</li>
<li><a
href="https://github.com/alibaba/hooks/commit/d92f995743242a12830ae85d4356391864ae79fa"><code>d92f995</code></a>
fix: resolves depsEqual performance issues (<a
href="https://redirect.github.com/alibaba/hooks/issues/2577">#2577</a>)
(<a
href="https://redirect.github.com/alibaba/hooks/issues/2578">#2578</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/alibaba/hooks/compare/v3.8.0...v3.8.1">compare
view</a></li>
</ul>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=ahooks&package-manager=npm_and_yarn&previous-version=3.8.0&new-version=3.8.1)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>